apiVersion: v1
kind: Service
metadata:
  name: salary-predictor-service
spec:
  selector:
    app: salary-predictor
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007  # Optional: You can let Kubernetes assign this if omitted
