name: Deploy to VM

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'src/**'
      - 'app.py'
      - 'model/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Copy files to VM
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/Mlops_Final/

      - name: Deploy on VM via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            cd ~/Mlops_Final
            docker build -t salary-predictor-app .
            docker stop salary-container || true
            docker rm salary-container || true
            docker run -d -p 5000:5000 --name salary-container salary-predictor-app
          EOF
