name: Retrain Model

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:     # Manual trigger from GitHub repo

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Retrain the model
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python src/train.py

      - name: Commit and push new model
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          if [ -f src/model.pkl ]; then
            git add src/model.pkl
            git commit -m "🔁 Retrained model - $(date +'%Y-%m-%d')" || echo "No changes to commit"
            git push
          else
            echo "❌ src/model.pkl not found — skipping commit."
          fi
