name: Continuous Deployment to VM

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app.py'
      - 'requirements.txt'
      - 'src/**'
      - 'model/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add VM to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VM_IP }} >> ~/.ssh/known_hosts

      - name: Copy project to VM
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.VM_USER }}@${{ secrets.VM_IP }}:~/Mlops_Final/

      - name: Deploy on remote VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_IP }} << 'EOF'
            cd ~/Mlops_Final
            docker stop salary-container || true
            docker rm salary-container || true
            docker build -t salary-predictor-app .
            docker run -d -p 5000:5000 --name salary-container salary-predictor-app
          EOF
