name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder deploy
        run: echo \"Deploy to Kubernetes or VM will go here.\"
